//
//  AppleSpatialScene.swift
//  SpatialMemory — Apple's own 2D→3D path, when the hardware can run it
//
//  ============================================================================
//  READ THIS BEFORE DEBUGGING ANYTHING IN HERE
//
//  This file is deliberately self-contained and touches nothing else. If it
//  fails to build, remove it from the target and the custom pipeline is exactly
//  as it was. Nothing in Sources/ depends on it; the one call site is behind an
//  `if #available` and a `do/catch`.
//
//  WHAT IT IS
//
//  visionOS 26 ships Apple's own spatial-scene generator:
//  `ImagePresentationComponent.Spatial3DImage` takes a flat photo, runs their
//  model, and hands RealityKit a scene with depth and motion parallax already
//  solved. On real hardware it will beat the custom DepthMesh + inpainting
//  pipeline, because it is the same model Photos uses and it was trained for
//  exactly this.
//
//  WHY IT DOES NOT REPLACE THE CUSTOM PIPELINE
//
//  From Apple's documentation, verbatim in substance: you cannot generate a
//  Spatial3DImage in the visionOS Simulator. You can construct one there, but
//  `generate()` THROWS.
//
//  That last detail is the one that matters, and it is better than the
//  assumption this project was built on. A throw is catchable. So this is not a
//  build-flag decision or a "device only" branch — it is a `try`, and when it
//  fails the custom pipeline picks the memory up in the same function. One
//  binary, best available result on whatever it happens to be running.
//
//  DOCUMENTED CONSTRAINTS on the source image, checked here up front so the
//  failure names itself instead of arriving as an opaque throw:
//    · at least 320 px on the shortest side
//    · at most 16,384 px on the longest
//    · aspect ratio between 1:3 and 3:1
//
//  Apple also notes that spatial scenes are generated by an AI algorithm and
//  "may contain visual artifacts" — worth remembering for this application in
//  particular, where an artefact is not a glitch but a wrong memory.
//  ============================================================================
//
//  Targets: Swift 5.10+, visionOS 26.0+ (the file compiles against lower
//  deployment targets; the API is gated by `@available`).
//

import CoreGraphics
import Foundation
import ImageIO
import RealityKit
import simd
// Direct import, not via ImageIO: this project builds with
// SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY, so `UTType`'s members only
// resolve if the defining module is imported in this file.
import UniformTypeIdentifiers

@available(visionOS 26.0, *)
public enum AppleSpatialScene {

    public enum Unsupported: LocalizedError {
        case undecodable
        case tooSmall(shortestSide: Int)
        case tooLarge(longestSide: Int)
        case aspectOutOfRange(Double)

        public var errorDescription: String? {
            switch self {
            case .undecodable:
                return "Those bytes are not an image Core Graphics can open."
            case let .tooSmall(side):
                return "Spatial scenes need at least 320 px on the shortest side; this is \(side)."
            case let .tooLarge(side):
                return "Spatial scenes allow at most 16,384 px on the longest side; this is \(side)."
            case let .aspectOutOfRange(ratio):
                return String(
                    format: "Spatial scenes need an aspect ratio between 1:3 and 3:1; this is %.2f:1.",
                    ratio
                )
            }
        }
    }

    /// Builds an entity presenting `data` as one of Apple's spatial scenes.
    ///
    /// Throws rather than returning nil, because every reason it can fail is
    /// worth reading: in the Simulator it is "generation is unavailable here",
    /// and on device it is almost always one of the size constraints.
    ///
    /// - Parameter position: where the scene sits relative to the immersive
    ///   space's origin. That origin is the floor beneath the wearer, so the
    ///   default puts the scene at roughly eye height, two metres out. The
    ///   custom container in `MemoryContainer` uses a different convention — its
    ///   origin is the head — so do not copy numbers between them.
    @MainActor
    public static func makeEntity(
        from data: Data,
        position: SIMD3<Float> = [0, 1.5, -2]
    ) async throws -> Entity {

        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else {
            throw Unsupported.undecodable
        }
        try validate(source)

        // TWO WAYS IN, and they are not equally well travelled.
        //
        // `init(contentsOf:)` takes a file URL and is the one Apple documents
        // first and demonstrates with. `init(imageSource:)` takes a CGImageSource
        // which, when it was built from Data rather than a file, has no backing
        // file at all. Whether the generator minds is not documented — so rather
        // than assume, try the file path first and keep the in-memory one as a
        // fallback. Whichever fails, the error reported is the one from the
        // path Apple actually documents.
        let spatial: ImagePresentationComponent.Spatial3DImage
        let scratch = try writeScratchFile(data, source: source)
        defer { try? FileManager.default.removeItem(at: scratch) }

        do {
            spatial = try await ImagePresentationComponent.Spatial3DImage(contentsOf: scratch)
        } catch {
            spatial = try await ImagePresentationComponent.Spatial3DImage(imageSource: source)
        }

        // In the Simulator it is `generate()` that throws, not the initializer —
        // which is exactly why the test has to be "did it work" rather than
        // "am I on a simulator".
        try await spatial.generate()

        var component = ImagePresentationComponent(spatial3DImage: spatial)

        // A component always offers `mono`, and only offers the spatial modes
        // once generation has actually produced something. Asking for a mode
        // that is not in the set leaves it presenting a flat picture, silently —
        // so the set is queried rather than assumed.
        if component.availableViewingModes.contains(.spatial3DImmersive) {
            component.desiredViewingMode = .spatial3DImmersive
        } else if component.availableViewingModes.contains(.spatial3D) {
            component.desiredViewingMode = .spatial3D
        }

        let entity = Entity()
        entity.name = "AppleSpatialScene"
        entity.position = position
        entity.components.set(component)
        return entity
    }

    // MARK: Scratch file

    /// Writes the bytes to a temporary file, keeping the ORIGINAL container's
    /// extension.
    ///
    /// The extension is taken from the source's own UTI rather than assumed:
    /// an iPhone photo is usually HEIC, and handing a decoder a `.jpg` that is
    /// really HEIC is a good way to get an opaque failure.
    static func writeScratchFile(_ data: Data, source: CGImageSource) throws -> URL {
        var ext = "jpg"
        if let uti = CGImageSourceGetType(source) as String?,
           let type = UTType(uti),
           let preferred = type.preferredFilenameExtension {
            ext = preferred
        }

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("spatial-source-\(UUID().uuidString)")
            .appendingPathExtension(ext)

        try data.write(to: url, options: .atomic)
        return url
    }

    // MARK: Constraints

    static func validate(_ source: CGImageSource) throws {
        guard let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
              width > 0, height > 0 else {
            throw Unsupported.undecodable
        }

        let shortest = min(width, height)
        let longest = max(width, height)
        guard shortest >= 320 else { throw Unsupported.tooSmall(shortestSide: shortest) }
        guard longest <= 16_384 else { throw Unsupported.tooLarge(longestSide: longest) }

        let ratio = Double(longest) / Double(shortest)
        guard ratio <= 3.0 else { throw Unsupported.aspectOutOfRange(ratio) }
    }
}
